# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add ka "k apply --recursive -f"
abbr --add kak "k apply -k"
abbr --add kaf "k apply -f"
abbr --add kk "k kustomize"
abbr --add ke "k exec -i -t"
abbr --add kl "k logs"
abbr --add kg "k get"
abbr --add kd "k describe"
abbr --add krm "k delete"
abbr --add kgp "k get pods"
abbr --add kdp "k describe pods"
abbr --add krmp "k delete pods"
abbr --add kad "k apply --recursive -f deployment"
abbr --add kakd "k apply -k deployment"
abbr --add kafd "k apply -f deployment"
abbr --add kkd "k kustomize deployment"
abbr --add ked "k exec -i -t deployment"
abbr --add kld "k logs -f deployment"
abbr --add kgd "k get deployment"
abbr --add kdd "k describe deployment"
abbr --add krmd "k delete deployment"
abbr --add kgss "k get statefulset"
abbr --add kdss "k describe statefulset"
abbr --add krmss "k delete statefulset"
abbr --add kgs "k get service"
abbr --add kds "k describe service"
abbr --add krms "k delete service"
abbr --add kgi "k get ingress"
abbr --add kdi "k describe ingress"
abbr --add krmi "k delete ingress"
abbr --add kgcm "k get configmap"
abbr --add kdcm "k describe configmap"
abbr --add krmcm "k delete configmap"
abbr --add kgsec "k get secret"
abbr --add kdsec "k describe secret"
abbr --add krmsec "k delete secret"
abbr --add kgno "k get nodes"
abbr --add kdno "k describe nodes"
abbr --add kgns "k get namespaces"
abbr --add kdns "k describe namespaces"
abbr --add krmns "k delete namespaces"
abbr --add kghr "k get helmrelease"
abbr --add kdhr "k describe helmrelease"
abbr --add krmhr "k delete helmrelease"
abbr --add kgk "k get kustomization"
abbr --add kdk "k describe kustomization"
abbr --add krmk "k delete kustomization"
abbr --add kgpvc "k get pvc"
abbr --add kdpvc "k describe pvc"
abbr --add krmpvc "k delete pvc"
abbr --add kgo "k get -o=wide"
abbr --add kgpo "k get pods -o=wide"
abbr --add kgdo "k get deployment -o=wide"
abbr --add kgsso "k get statefulset -o=wide"
abbr --add kgso "k get service -o=wide"
abbr --add kgio "k get ingress -o=wide"
abbr --add kgcmo "k get configmap -o=wide"
abbr --add kgseco "k get secret -o=wide"
abbr --add kgnoo "k get nodes -o=wide"
abbr --add kgnso "k get namespaces -o=wide"
abbr --add kghro "k get helmrelease -o=wide"
abbr --add kgko "k get kustomization -o=wide"
abbr --add kgpvco "k get pvc -o=wide"
abbr --add kgall "k get --all-namespaces"
abbr --add kgpall "k get pods --all-namespaces"
abbr --add kdpall "k describe pods --all-namespaces"
abbr --add kadall "k apply --recursive -f deployment --all-namespaces"
abbr --add kakdall "k apply -k deployment --all-namespaces"
abbr --add kafdall "k apply -f deployment --all-namespaces"
abbr --add kkdall "k kustomize deployment --all-namespaces"
abbr --add kedall "k exec -i -t deployment --all-namespaces"
abbr --add kldall "k logs -f deployment --all-namespaces"
abbr --add kgdall "k get deployment --all-namespaces"
abbr --add kddall "k describe deployment --all-namespaces"
abbr --add kgssall "k get statefulset --all-namespaces"
abbr --add kdssall "k describe statefulset --all-namespaces"
abbr --add kgsall "k get service --all-namespaces"
abbr --add kdsall "k describe service --all-namespaces"
abbr --add kgiall "k get ingress --all-namespaces"
abbr --add kdiall "k describe ingress --all-namespaces"
abbr --add kgcmall "k get configmap --all-namespaces"
abbr --add kdcmall "k describe configmap --all-namespaces"
abbr --add kgsecall "k get secret --all-namespaces"
abbr --add kdsecall "k describe secret --all-namespaces"
abbr --add kgnsall "k get namespaces --all-namespaces"
abbr --add kdnsall "k describe namespaces --all-namespaces"
abbr --add kghrall "k get helmrelease --all-namespaces"
abbr --add kdhrall "k describe helmrelease --all-namespaces"
abbr --add kgkall "k get kustomization --all-namespaces"
abbr --add kdkall "k describe kustomization --all-namespaces"
abbr --add kgpvcall "k get pvc --all-namespaces"
abbr --add kdpvcall "k describe pvc --all-namespaces"
abbr --add kgw "k get --watch"
abbr --add kgpw "k get pods --watch"
abbr --add kgdw "k get deployment --watch"
abbr --add kgssw "k get statefulset --watch"
abbr --add kgsw "k get service --watch"
abbr --add kgiw "k get ingress --watch"
abbr --add kgcmw "k get configmap --watch"
abbr --add kgsecw "k get secret --watch"
abbr --add kgnow "k get nodes --watch"
abbr --add kgnsw "k get namespaces --watch"
abbr --add kghrw "k get helmrelease --watch"
abbr --add kgkw "k get kustomization --watch"
abbr --add kgpvcw "k get pvc --watch"
abbr --add kgoall "k get -o=wide --all-namespaces"
abbr --add kgpoall "k get pods -o=wide --all-namespaces"
abbr --add kgdoall "k get deployment -o=wide --all-namespaces"
abbr --add kgssoall "k get statefulset -o=wide --all-namespaces"
abbr --add kgsoall "k get service -o=wide --all-namespaces"
abbr --add kgioall "k get ingress -o=wide --all-namespaces"
abbr --add kgcmoall "k get configmap -o=wide --all-namespaces"
abbr --add kgsecoall "k get secret -o=wide --all-namespaces"
abbr --add kgnsoall "k get namespaces -o=wide --all-namespaces"
abbr --add kghroall "k get helmrelease -o=wide --all-namespaces"
abbr --add kgkoall "k get kustomization -o=wide --all-namespaces"
abbr --add kgpvcoall "k get pvc -o=wide --all-namespaces"
abbr --add kgallo "k get --all-namespaces -o=wide"
abbr --add kgpallo "k get pods --all-namespaces -o=wide"
abbr --add kgdallo "k get deployment --all-namespaces -o=wide"
abbr --add kgssallo "k get statefulset --all-namespaces -o=wide"
abbr --add kgsallo "k get service --all-namespaces -o=wide"
abbr --add kgiallo "k get ingress --all-namespaces -o=wide"
abbr --add kgcmallo "k get configmap --all-namespaces -o=wide"
abbr --add kgsecallo "k get secret --all-namespaces -o=wide"
abbr --add kgnsallo "k get namespaces --all-namespaces -o=wide"
abbr --add kghrallo "k get helmrelease --all-namespaces -o=wide"
abbr --add kgkallo "k get kustomization --all-namespaces -o=wide"
abbr --add kgpvcallo "k get pvc --all-namespaces -o=wide"
abbr --add kgallw "k get --all-namespaces --watch"
abbr --add kgpallw "k get pods --all-namespaces --watch"
abbr --add kgdallw "k get deployment --all-namespaces --watch"
abbr --add kgssallw "k get statefulset --all-namespaces --watch"
abbr --add kgsallw "k get service --all-namespaces --watch"
abbr --add kgiallw "k get ingress --all-namespaces --watch"
abbr --add kgcmallw "k get configmap --all-namespaces --watch"
abbr --add kgsecallw "k get secret --all-namespaces --watch"
abbr --add kgnsallw "k get namespaces --all-namespaces --watch"
abbr --add kghrallw "k get helmrelease --all-namespaces --watch"
abbr --add kgkallw "k get kustomization --all-namespaces --watch"
abbr --add kgpvcallw "k get pvc --all-namespaces --watch"
abbr --add kgwall "k get --watch --all-namespaces"
abbr --add kgpwall "k get pods --watch --all-namespaces"
abbr --add kgdwall "k get deployment --watch --all-namespaces"
abbr --add kgsswall "k get statefulset --watch --all-namespaces"
abbr --add kgswall "k get service --watch --all-namespaces"
abbr --add kgiwall "k get ingress --watch --all-namespaces"
abbr --add kgcmwall "k get configmap --watch --all-namespaces"
abbr --add kgsecwall "k get secret --watch --all-namespaces"
abbr --add kgnswall "k get namespaces --watch --all-namespaces"
abbr --add kghrwall "k get helmrelease --watch --all-namespaces"
abbr --add kgkwall "k get kustomization --watch --all-namespaces"
abbr --add kgpvcwall "k get pvc --watch --all-namespaces"
abbr --add kgn "k get --namespace"
abbr --add kdn "k describe --namespace"
abbr --add krmn "k delete --namespace"
abbr --add kgpn "k get pods --namespace"
abbr --add kdpn "k describe pods --namespace"
abbr --add krmpn "k delete pods --namespace"
abbr --add kadn "k apply --recursive -f deployment --namespace"
abbr --add kakdn "k apply -k deployment --namespace"
abbr --add kafdn "k apply -f deployment --namespace"
abbr --add kkdn "k kustomize deployment --namespace"
abbr --add kedn "k exec -i -t deployment --namespace"
abbr --add kldn "k logs -f deployment --namespace"
abbr --add kgdn "k get deployment --namespace"
abbr --add kddn "k describe deployment --namespace"
abbr --add krmdn "k delete deployment --namespace"
abbr --add kgssn "k get statefulset --namespace"
abbr --add kdssn "k describe statefulset --namespace"
abbr --add krmssn "k delete statefulset --namespace"
abbr --add kgsn "k get service --namespace"
abbr --add kdsn "k describe service --namespace"
abbr --add krmsn "k delete service --namespace"
abbr --add kgin "k get ingress --namespace"
abbr --add kdin "k describe ingress --namespace"
abbr --add krmin "k delete ingress --namespace"
abbr --add kgcmn "k get configmap --namespace"
abbr --add kdcmn "k describe configmap --namespace"
abbr --add krmcmn "k delete configmap --namespace"
abbr --add kgsecn "k get secret --namespace"
abbr --add kdsecn "k describe secret --namespace"
abbr --add krmsecn "k delete secret --namespace"
abbr --add kghrn "k get helmrelease --namespace"
abbr --add kdhrn "k describe helmrelease --namespace"
abbr --add krmhrn "k delete helmrelease --namespace"
abbr --add kgkn "k get kustomization --namespace"
abbr --add kdkn "k describe kustomization --namespace"
abbr --add krmkn "k delete kustomization --namespace"
abbr --add kgpvcn "k get pvc --namespace"
abbr --add kdpvcn "k describe pvc --namespace"
abbr --add krmpvcn "k delete pvc --namespace"
abbr --add kgon "k get -o=wide --namespace"
abbr --add kgpon "k get pods -o=wide --namespace"
abbr --add kgdon "k get deployment -o=wide --namespace"
abbr --add kgsson "k get statefulset -o=wide --namespace"
abbr --add kgson "k get service -o=wide --namespace"
abbr --add kgion "k get ingress -o=wide --namespace"
abbr --add kgcmon "k get configmap -o=wide --namespace"
abbr --add kgsecon "k get secret -o=wide --namespace"
abbr --add kghron "k get helmrelease -o=wide --namespace"
abbr --add kgkon "k get kustomization -o=wide --namespace"
abbr --add kgpvcon "k get pvc -o=wide --namespace"
abbr --add kgwn "k get --watch --namespace"
abbr --add kgpwn "k get pods --watch --namespace"
abbr --add kgdwn "k get deployment --watch --namespace"
abbr --add kgsswn "k get statefulset --watch --namespace"
abbr --add kgswn "k get service --watch --namespace"
abbr --add kgiwn "k get ingress --watch --namespace"
abbr --add kgcmwn "k get configmap --watch --namespace"
abbr --add kgsecwn "k get secret --watch --namespace"
abbr --add kghrwn "k get helmrelease --watch --namespace"
abbr --add kgkwn "k get kustomization --watch --namespace"
abbr --add kgpvcwn "k get pvc --watch --namespace"

# Tools for accessing all information
abbr --add kga "k get all"
abbr --add kgaa "k get all --all-namespaces"

# Scaling shortcuts
abbr --add ksd "k scale deployment"
abbr --add kssts "k scale statefulset"⏎
