#!/usr/bin/env zsh
#
# Only including a shebang to trigger editors to use shell syntax highlighting
#
# Copyright 2006-2022 Joseph Block <jpb@unixorn.net>
#
# BSD licensed, see LICENSE.txt in this repository.

# Check if a command exists
function can_haz() {
  which "$@" > /dev/null 2>&1
}

alias cputop="top -o cpu"
alias ll='ls -alFh --color=always --group-directories-first'
alias la='ls -a'
alias l='ls -CF'

# shellcheck disable=SC2142
alias historysummary="history | awk '{a[\$2]++} END{for(i in a){printf \"%5d\t%s\n\",a[i],i}}' | sort -rn | head"

export VISUAL=micro

# Clean up files that have the wrong line endings
alias mac2unix="tr '\015' '\012'"
alias unix2mac="tr '\012' '\015'"

# Strip color codes from commands that insist on spewing them so we can
# pipe them into files cleanly.
alias stripcolors='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"'

# On the rare occasions I don't want to continue an interrupted download
# I can always delete the incomplete fragment explicitly. I usually just
# want to complete it.
alias wget="wget -c"

# Dump the last 20 history entries to make !number more convenient to use.
alias zh="fc -l -d -D"

# Help the lazy typists again.
alias ..="cd .."
alias ...="cd ../.."

# Micro
alias mc='micro'

#go-task
if can_haz go-task; then
	alias task='go-task'
fi

#kubectl
if can_haz kubectl; then
	alias kdhr='kubectl describe hr'
	alias kdelhr='kubectl delete hr'
fi

# function to log into lxc containers
function lexec() {
	lxc exec $1 -- sudo -iu chris
}
