#!/bin/zsh
#
# Only including a shebang to trigger editors to use shell syntax highlighting
#
# Copyright 2006-2021 Joseph Block <jpb@unixorn.net>
#
# The ZSH Starter Kit allows you to replace the curated plugins list it
# ships with with a custom one by creating a file named .zsh-quickstart-local-plugins.
#
# This is to make it easier to customize without having to maintain a separate
# fork of the starter kit.
#
# This example file duplicates the list of plugins that shipped with the
# kit as of 2020-01-01.

ZGEN_LOADED=()
ZGEN_COMPLETIONS=()

if [[ ! -f "$CONFIG_PATH/.zsh-quickstart-no-omz" ]]; then
  zgenom oh-my-zsh
fi

# If you want to customize your plugin list, create a file named
# .zsh-quickstart-local-plugins in your home directory. That file will be sourced
# during startup *instead* of running this load-starter-plugin-list function,
# so make sure to include everything from this function that you want to
# keep.
#
# To make customizing easier, there's a .zsh-quickstart-local-plugins-example
# file at the top level of the zsh-quickstart-kit repository that you can copy
# as a starting point. This keeps you from having to maintain a fork of
# the quickstart kit.

# If zsh-syntax-highlighting is bundled after zsh-history-substring-search,
# they break, so get the order right.
zgenom load zsh-users/zsh-syntax-highlighting
zgenom load zsh-users/zsh-history-substring-search

# Set keystrokes for substring searching
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Automatically run zgenom update and zgenom selfupdate every 7 days.
zgenom load unixorn/autoupdate-zgenom

# Warn you when you run a command that you've set an alias for without
# using the alias.
zgenom load djui/alias-tips

if [[ ! -f "$CONFIG_PATH/.zsh-quickstart-no-omz" ]]; then
  # Load some oh-my-zsh plugins
  zgenom oh-my-zsh plugins/pip
  zgenom oh-my-zsh plugins/sudo
  zgenom oh-my-zsh plugins/colored-man-pages
  zgenom oh-my-zsh plugins/git
  zgenom oh-my-zsh plugins/github
  zgenom oh-my-zsh plugins/python
  zgenom oh-my-zsh plugins/rsync
  zgenom oh-my-zsh plugins/kubectl
  zgenom oh-my-zsh plugins/helm
  zgenom oh-my-zsh plugins/terraform
fi

# LXD Completions
if command -v lxd &> /dev/null
then
  zgenom load  endaaman/lxd-completion-zsh
fi

zgenom load chrissicool/zsh-256color

# Load more completion files for zsh from the zsh-lovers github repo.
zgenom load zsh-users/zsh-completions src

# Load me last
GENCOMPL_FPATH=$HOME/.zsh/complete

# Add Fish-like autosuggestions to your ZSH.
# zgenom load zsh-users/zsh-autosuggestions

# k is a zsh script / plugin to make directory listings more readable,
# adding a bit of color and some git status information on files and
# directories.
#zgenom load supercrabtree/k

# p10k is faster and what I'm using now, so it is the new default
zgenom load romkatv/powerlevel10k powerlevel10k


# Save it all to init script
zgenom save
